In [22]:
def load_json(filename):
    '''
    Load the given .json files for STAT-628-Module-3
    '''
    res = []
    with open(filename, 'r') as f:
        try:
            while True:
                line = f.readline()
                if line:
                    res.append(json.loads(line))
                else:
                    break
        except:
            f.close()
    res = pd.DataFrame.from_dict(res)
    return res

In [32]:
import json
import pandas as pd

In [23]:
business = load_json('business.json')

In [24]:
review = load_json('review.json')

In [25]:
review

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,Q1sbwvVQXV2734tPgoKj4Q,hG7b0MtEbXx5QzbzE6C_VA,ujmEBvifdJM6h6RLv4wQIg,1.0,6,1,0,Total bill for this horrible service? Over $8G...,2013-05-07 04:34:36
1,GJXCdrto3ASJOqKeVWPi6Q,yXQM5uF2jS6es16SJzNHfg,NZnhc2sEQy3RmzKTZnqtwQ,5.0,0,0,0,I *adore* Travis at the Hard Rock's new Kelly ...,2017-01-14 21:30:33
2,2TzJjDVDEuAW6MR5Vuc1ug,n6-Gk65cPZL6Uz8qRm3NYw,WTqjgwHlXbSFevF32_DJVw,5.0,3,0,0,I have to say that this office really has it t...,2016-11-09 20:09:03
3,yi0R0Ugj_xUx_Nek0-_Qig,dacAIZ6fTM6mqwW5uxkskg,ikCg8xy5JIg_NGPx-MSIDA,5.0,0,0,0,Went in for a lunch. Steak sandwich was delici...,2018-01-09 20:56:38
4,11a8sVPMUFtaC7_ABRkmtw,ssoyf2_x0EQMed6fgHeMyQ,b1b1eb3uo-w561D0ZfCEiQ,1.0,7,0,0,Today was my second out of three sessions I ha...,2018-01-30 23:07:38
...,...,...,...,...,...,...,...,...,...
6685895,0pCaq1hqAViS2N6ldlp_sQ,Xu_YazIajfsc7SRj1wJ6Mg,RXBFk3tVBxiTf3uOt9KExQ,5.0,1,0,0,I have been coming here for years and this pla...,2018-07-03 12:17:27
6685896,jPCXuSBbI_cPocgoNBhdkg,V6BjjQICDO4q7TT3ZhaPWw,yA6dKNm_zl1ucZCnwW8ZCg,1.0,13,11,5,I think this owner and the owner of Amy's Baki...,2013-05-22 15:32:08
6685897,zwzO3yPdGbdgGy3-XQ0SWg,PFiIECX8wuvi7P-1mCvIjA,a192hdM0_UVCYLwPJv1Qwg,5.0,0,0,0,"Off the grid Mexican in Vegas. Very tasty, qua...",2018-11-13 21:15:20
6685898,o8Nc2BJhKJXM6tRHJDRuPA,wu5R5_N7q5iqCBh6NBX26Q,kOo4ZY2UQAX4j312mzQ8mA,5.0,1,1,1,We hired Taco Naco to cater our family party a...,2018-08-13 18:09:16
6685899,OKmOLFwtI-NjofTHAGzv1Q,Ej3mCvjcwVXCSPB_avIfjQ,PkqN5st3zZ_Xce_5QlBtNQ,3.0,2,0,0,Having just come back from Hawaii a few months...,2018-11-12 20:25:32

In [31]:
review.describe()

              stars        useful         funny          cool
count  6.685900e+06  6.685900e+06  6.685900e+06  6.685900e+06
mean   3.716199e+00  1.354134e+00  4.827667e-01  5.787708e-01
std    1.463643e+00  3.700192e+00  2.378646e+00  2.359024e+00
min    1.000000e+00 -1.000000e+00  0.000000e+00 -1.000000e+00
25%    3.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
50%    4.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00
75%    5.000000e+00  2.000000e+00  0.000000e+00  1.000000e+00
max    5.000000e+00  1.241000e+03  1.290000e+03  5.060000e+02

In [26]:
user = load_json("user.json")

In [27]:
user

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,l6BmjZMeQD3rDxWUbiAiow,Rashmi,95,2013-10-08 23:11:33,84,17,25,"2015,2016,2017","c78V-rj8NQcQjOI8KP3UEA, alRMgPcngYSCJ5naFRBz5g...",5,...,0,0,0,0,1,1,1,1,2,0
1,4XChL029mKr5hydo79Ljxg,Jenna,33,2013-02-21 22:29:06,48,22,16,,"kEBTgDvFX754S68FllfCaA, aB2DynOxNOJK9st2ZeGTPg...",4,...,0,0,0,0,0,0,1,1,0,0
2,bc8C_eETBWL0olvFSJJd0w,David,16,2013-10-04 00:16:10,28,8,10,,"4N-HU_T32hLENLntsNKNBg, pSY2vwWLgWfGVAAiKQzMng...",0,...,0,0,0,0,1,0,0,0,0,0
3,dD0gZpBctWGdWo9WlGuhlA,Angela,17,2014-05-22 15:57:30,30,4,14,,"RZ6wS38wnlXyj-OOdTzBxA, l5jxZh1KsgI8rMunm-GN6A...",5,...,0,0,0,0,0,2,0,0,1,0
4,MM4RJAeH6yuaN8oZDSt0RA,Nancy,361,2013-10-23 07:02:50,1114,279,665,"2015,2016,2017,2018","mbwrZ-RS76V1HoJ0bF_Geg, g64lOV39xSLRZO0aQQ6DeQ...",39,...,1,0,0,1,16,57,80,80,25,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1637133,oC4BjbB4I-wx5KBAO1k2Gg,Jiaxin,2,2016-02-24 19:28:47,0,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1637134,LKd_-BT2GMWp8_1ho18kOg,Wes,8,2017-02-25 23:34:05,0,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1637135,ib_elCBhGOamS0AALkh4Og,Lee,4,2009-08-19 22:08:16,8,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1637136,WV27LoSFDG_YmiDKTLKKLA,Melissa,1,2018-10-15 17:07:43,1,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0
1637137,agVqH9xDhNw8n7ve66H1Uw,Erin,1,2016-03-03 21:56:06,0,0,0,,None,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
tip = load_json("tip.json")

In [29]:
tip

,user_id,business_id,text,date,compliment_count
0,UPw5DWs_b-e2JRBS-t37Ag,VaKXUpmWTTWDKbpJ3aQdMw,"Great for watching games, ufc, and whatever el...",2014-03-27 03:51:24,0
1,Ocha4kZBHb4JK0lOWvE0sg,OPiPeoJiv92rENwbq76orA,Happy Hour 2-4 daily with 1/2 price drinks and...,2013-05-25 06:00:56,0
2,jRyO2V1pA4CdVVqCIOPc1Q,5KheTjYPu1HcQzQFtm4_vw,Good chips and salsa. Loud at times. Good serv...,2011-12-26 01:46:17,0
3,FuTJWFYm4UKqewaosss1KA,TkoyGi8J7YFjA6SbaRzrxg,The setting and decoration here is amazing. Co...,2014-03-23 21:32:49,0
4,LUlKtaM3nXd-E4N4uOk_fQ,AkL6Ous6A1atZejfZXn1Bg,Molly is definately taking a picture with Sant...,2012-10-06 00:19:27,0
...,...,...,...,...,...
1223089,nus5X9JKgU_SzfAL4vhJrg,qdwwiRKwnhdlr9QcgJuzbg,"Very good class, great instructor!!",2018-08-05 20:58:09,0
1223090,95wqYGU6-OiHqRPZP0uAWw,wrs4Zbz17q_G49AIRxRPVw,Excellent food,2018-08-15 18:05:22,0
1223091,HtLaONYabidSxMS1eGHcXA,wEc4JE2NYQr1RnGjGr4q7w,Jess is the best bartender!! Go check her out!,2018-10-02 03:34:58,0
1223092,T4R5ZKfcGt1GIAgjCh67eA,n5Hc_iMVkyxcS0SXiBCbOQ,Excellent food and AMAZING service by Anneliese!!,2018-10-13 16:57:50,0
1223093,2Ag223bd4OtQOnc-F067rQ,wEoaR5WKNtLOLyR1z0TYdg,Funnnnn!!!,2018-11-10 03:17:18,0

In [30]:
business

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,1SWheh84yJXfytovILXOAQ,Arizona Biltmore Golf Club,2818 E Camino Acequia Drive,Phoenix,AZ,85016,33.522143,-112.018481,3.0,5,0,{'GoodForKids': 'False'},"Golf, Active Life",None
1,QXAEGFB4oINsVuTFxEYKFQ,Emerald Chinese Restaurant,30 Eglinton Avenue W,Mississauga,ON,L5R 3E7,43.605499,-79.652289,2.5,128,1,"{'RestaurantsReservations': 'True', 'GoodForMe...","Specialty Food, Restaurants, Dim Sum, Imported...","{'Monday': '9:0-0:0', 'Tuesday': '9:0-0:0', 'W..."
2,gnKjwL_1w79qoiV3IC_xQQ,Musashi Japanese Restaurant,"10110 Johnston Rd, Ste 15",Charlotte,NC,28210,35.092564,-80.859132,4.0,170,1,"{'GoodForKids': 'True', 'NoiseLevel': 'u'avera...","Sushi Bars, Restaurants, Japanese","{'Monday': '17:30-21:30', 'Wednesday': '17:30-..."
3,xvX2CttrVhyG2z1dFg_0xw,Farmers Insurance - Paul Lorenz,"15655 W Roosevelt St, Ste 237",Goodyear,AZ,85338,33.455613,-112.395596,5.0,3,1,None,"Insurance, Financial Services","{'Monday': '8:0-17:0', 'Tuesday': '8:0-17:0', ..."
4,HhyxOkGAM07SRYtlQ4wMFQ,Queen City Plumbing,"4209 Stuart Andrew Blvd, Ste F",Charlotte,NC,28217,35.190012,-80.887223,4.0,4,1,"{'BusinessAcceptsBitcoin': 'False', 'ByAppoint...","Plumbing, Shopping, Local Services, Home Servi...","{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192604,nqb4kWcOwp8bFxzfvaDpZQ,Sanderson Plumbing,,North Las Vegas,NV,89032,36.213732,-115.177059,5.0,9,1,{'BusinessAcceptsCreditCards': 'True'},"Water Purification Services, Water Heater Inst...","{'Monday': '0:0-0:0', 'Tuesday': '0:0-0:0', 'W..."
192605,vY2nLU5K20Pee-FdG0br1g,Chapters,17440 Yonge Street,Newmarket,ON,L3Y 6Y9,44.052658,-79.481850,4.5,3,1,"{'RestaurantsPriceRange2': '2', 'BikeParking':...","Books, Mags, Music & Video, Shopping",None
192606,MiEyUDKTjeci5TMfxVZPpg,Phoenix Pavers,21230 N 22nd St,Phoenix,AZ,85024,33.679992,-112.035569,4.5,14,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Contractors, Landscaping, Mason...","{'Monday': '7:0-15:0', 'Tuesday': '7:0-15:0', ..."
192607,zNMupayB2jEHVDOji8sxoQ,Beasley's Barber Shop,4406 E Main St,Mesa,AZ,85205,33.416137,-111.735743,4.5,15,1,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Beauty & Spas, Barbers","{'Tuesday': '8:30-17:30', 'Wednesday': '8:30-1..."
192608,c1f_VAX1KIK8-JoVhjbYOw,Oriental Relax,3735 S Las Vegas Blvd,Las Vegas,NV,89109,36.107267,-115.171920,4.0,3,0,"{'BikeParking': 'False', 'RestaurantsPriceRang...","Massage, Beauty & Spas","{'Monday': '10:0-0:0', 'Tuesday': '10:0-0:0', ..."

In [48]:
ice_cream = business.loc[(business['categories'] == 'Ice Cream & Frozen Yogurt, Food') | (business['categories'] == 'Food, Ice Cream & Frozen Yogurt'), :]
ice_cream

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
259,9FPEg18SyYsKgbWZ0XDysQ,Carolina Cones,20801 N Main St,Cornelius,NC,28031,35.491159,-80.858233,4.5,36,1,"{'BusinessParking': '{'garage': False, 'street...","Food, Ice Cream & Frozen Yogurt","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'..."
712,7gERr4qY9GOIAr8EDFTtvw,Razzleberriez,"13706 W Bell Rd, Ste 14",Surprise,AZ,85374,33.639748,-112.352684,3.5,25,0,"{'RestaurantsPriceRange2': '1', 'BusinessParki...","Food, Ice Cream & Frozen Yogurt","{'Monday': '12:0-22:0', 'Tuesday': '12:0-22:0'..."
849,_9u7I2RN0NEJnWaP2zhWsQ,Paciugo Gelato,"2530 W Happy Valley Rd, Ste 1271",Phoenix,AZ,85085,33.712971,-112.113016,3.5,6,0,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Food, Ice Cream & Frozen Yogurt",None
1339,ghc7Yqr7RkNbj3ydTpGuRQ,Tutti Bella Yogurt,"10670 Southern Highlands Pkwy, Ste 103",Las Vegas,NV,89141,35.996879,-115.207547,4.5,5,0,"{'RestaurantsPriceRange2': '1', 'BusinessAccep...","Ice Cream & Frozen Yogurt, Food",None
1562,3vxNIpEg5SmmInek0b7ulQ,The Frozen Isle,"101 S Tryon St, Ste 10",Charlotte,NC,28280,35.226327,-80.842936,4.5,11,0,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Ice Cream & Frozen Yogurt, Food",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190630,2Yhi7D3Y50P221Tm-KJ_tA,Jolly Rolls Ice Cream,2136 Ayrsley Town Blvd,Charlotte,NC,28273,35.138382,-80.934490,4.0,14,0,"{'BusinessAcceptsCreditCards': 'True', 'Caters...","Food, Ice Cream & Frozen Yogurt","{'Monday': '0:0-0:0', 'Tuesday': '12:0-21:0', ..."
191106,VpRuQv89NJwSVPPprXQH2A,Scoops,"6885 Aliante Pkwy, Ste 107",North Las Vegas,NV,89084,36.285834,-115.179239,3.5,53,1,"{'WiFi': ''no'', 'BusinessAcceptsCreditCards':...","Ice Cream & Frozen Yogurt, Food","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'..."
191160,ZhRo4cD5w7lQZzHvpL6PaQ,Chill-N-Yogurt,3310 E Flamingo Rd,Las Vegas,NV,89121,36.115598,-115.102678,4.0,19,0,"{'BusinessAcceptsCreditCards': 'True', 'WiFi':...","Ice Cream & Frozen Yogurt, Food","{'Monday': '11:30-22:0', 'Tuesday': '11:30-22:..."
191456,U3dfIC7Zj8umDs__dDJl2Q,Thrifty Ice Cream,2580 Wigwam Pkwy,Henderson,NV,89074,36.036066,-115.099731,4.0,150,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Food, Ice Cream & Frozen Yogurt","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'..."
192294,P_1ojkLpCsM8cpuiKlZnAg,Yogurtini,"15601 W Bell Rd, Ste 208",Surprise,AZ,85374,33.637055,-112.398109,4.5,59,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Ice Cream & Frozen Yogurt, Food","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'..."

In [52]:
ice_cream_review = review.loc[review["business_id"].isin(ice_cream["business_id"]),:]

In [53]:
ice_cream_review

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
41,8swMTt9IXycp15r3WlCEmg,ITSnuLOu81doC5GGT5NMSQ,RbrZJEf8TlnP7RHaKnCtIQ,3.0,2,0,1,One day after I satisfy my frozen yogurt cravi...,2013-11-14 04:55:17
77,9X9G_UAQN5W3mmspIjsLXA,hTZb1INhnCG8URaFywVoYQ,nDaW2hhQV5KYiGH7HzAOcg,3.0,1,0,1,I stumbled upon this ice cream store and seein...,2016-12-04 02:34:48
497,oNng44B6qzKWpcsbfKPleg,3Uv0dGI2IXJb2OUj8R2GJA,RbrZJEf8TlnP7RHaKnCtIQ,5.0,4,2,2,"After a spontaneous visit to Piccadilly, I am ...",2013-09-04 02:21:22
851,8D0qp04cQWpyMn2MxAa6qg,PhaiUt5shE1xQLPr_a1OrQ,nDaW2hhQV5KYiGH7HzAOcg,5.0,0,0,1,Perfect treat this summer... Great service as ...,2018-06-08 22:12:03
886,aEA-E6_De1pdLej7YyhWZA,xZaDDTBqSTRtAZJXtiOiEA,ghWwqlRd1MaWz8hfgZ8Vsw,4.0,2,0,0,I liked it and it was 33 degrees outside. I us...,2009-10-13 10:20:31
...,...,...,...,...,...,...,...,...,...
6683322,g9EFKRoET7WvIziZVhO5ew,VsWzqAHw0EOm75-_UVRHxg,FEq-DW4QwBW8-7w6PajTNQ,5.0,1,1,1,"When I walked in, I thought this place reminde...",2015-03-30 06:37:04
6683358,AI79W3de8yHESP4jfypixA,AXrouzqDq0yTGObjHuMAdQ,FEq-DW4QwBW8-7w6PajTNQ,5.0,0,0,0,"Friendly staff and high quality ice cream, I d...",2017-06-04 22:28:11
6683810,UZQfVFNtX8BiFE_6Qh7I2A,Gfs5SikMVkby2Qy4bXAUAA,YvxQOMstU2MVDr2uNHs_vw,5.0,0,0,0,Great ice cream. Their roasted pistachio is th...,2018-10-31 12:21:37
6683860,Dvwu-80NL443qUl0m5cy8w,yV07xdQPCi9XzDwnRp7QrQ,zHYjts6JqKBiKM5ZbO8eHA,5.0,1,1,1,The line was long but it moved fast. The staff...,2018-07-16 20:16:21
6684570,EUcKDyKGLSxb1ShbsPQ36A,t-YzhzJ8JV3sFf5gsu2rbg,_Bwk9Zl-xFHWA_7TOBWR-A,2.0,0,0,0,"I'm not a certified froyo expert, but I have m...",2012-08-05 17:12:22

In [58]:
result = pd.merge(ice_cream,ice_cream_review,how = "outer",on = "business_id")
result

,business_id,name,address,city,state,postal_code,latitude,longitude,stars_x,review_count,...,categories,hours,review_id,user_id,stars_y,useful,funny,cool,text,date
0,9FPEg18SyYsKgbWZ0XDysQ,Carolina Cones,20801 N Main St,Cornelius,NC,28031,35.491159,-80.858233,4.5,36,...,"Food, Ice Cream & Frozen Yogurt","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",f9feP-Y-o--4vvPToiW8VQ,iBC1SyHZBOO55tTsdSdfHA,5.0,1,0,0,Best ice cream at the lake. Great place to t...,2015-07-16 13:24:01
1,9FPEg18SyYsKgbWZ0XDysQ,Carolina Cones,20801 N Main St,Cornelius,NC,28031,35.491159,-80.858233,4.5,36,...,"Food, Ice Cream & Frozen Yogurt","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",GIiAUcUxQu94Swa9UWJj_A,FhqgZHUjzV6x9uYNs05Q5A,4.0,0,0,0,Lots of flavors!! They allow ya to try any of ...,2018-04-28 01:07:42
2,9FPEg18SyYsKgbWZ0XDysQ,Carolina Cones,20801 N Main St,Cornelius,NC,28031,35.491159,-80.858233,4.5,36,...,"Food, Ice Cream & Frozen Yogurt","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",JoXg3Yz4upStaYPFPZq98A,HptInOCjRLz9ddpkbaZpeQ,5.0,1,0,0,I took my wife and two kids here on a Friday n...,2016-07-15 13:40:05
3,9FPEg18SyYsKgbWZ0XDysQ,Carolina Cones,20801 N Main St,Cornelius,NC,28031,35.491159,-80.858233,4.5,36,...,"Food, Ice Cream & Frozen Yogurt","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",92YuNk9RqhWWqKhlh_4ALA,FEricOEx00OGrNOt8lUZhw,4.0,0,0,0,Cute local ice cream shop in Cornelius. The s...,2014-05-27 18:27:22
4,9FPEg18SyYsKgbWZ0XDysQ,Carolina Cones,20801 N Main St,Cornelius,NC,28031,35.491159,-80.858233,4.5,36,...,"Food, Ice Cream & Frozen Yogurt","{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",CpPWtL7bCSCGWdHAdato9g,5b59DMCxPWn-c2b6q50P7w,5.0,0,0,0,We love Carolina Cones. They have a great are...,2017-10-25 04:56:45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20222,P_1ojkLpCsM8cpuiKlZnAg,Yogurtini,"15601 W Bell Rd, Ste 208",Surprise,AZ,85374,33.637055,-112.398109,4.5,59,...,"Ice Cream & Frozen Yogurt, Food","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",pS9KI4ibwfINoxeTB902_A,QbDJB-4XAxn3BGwi6Rrzjw,5.0,0,0,0,I love this location out of all the yogurtinis...,2017-08-27 00:10:46
20223,P_1ojkLpCsM8cpuiKlZnAg,Yogurtini,"15601 W Bell Rd, Ste 208",Surprise,AZ,85374,33.637055,-112.398109,4.5,59,...,"Ice Cream & Frozen Yogurt, Food","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",RLsmK7kOQwqf9Znudn3vlg,Xga2KDIy2wfkdh8led3WPA,5.0,0,0,0,"I love this place, very friendly staff and gre...",2018-09-22 05:58:25
20224,P_1ojkLpCsM8cpuiKlZnAg,Yogurtini,"15601 W Bell Rd, Ste 208",Surprise,AZ,85374,33.637055,-112.398109,4.5,59,...,"Ice Cream & Frozen Yogurt, Food","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",qUDEz0PCLmjjip54h6CScw,lpgjORUHhRVEcvPIae0pBg,5.0,0,0,0,This really is the best frozen yogurt place th...,2015-01-03 04:52:22
20225,P_1ojkLpCsM8cpuiKlZnAg,Yogurtini,"15601 W Bell Rd, Ste 208",Surprise,AZ,85374,33.637055,-112.398109,4.5,59,...,"Ice Cream & Frozen Yogurt, Food","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",cPgwrihN2moAcmtfmn_32A,I7AGpdVcY0-CPJDDl-jU_w,5.0,0,0,0,My kids and I love to go to Yogurtini. Staff i...,2018-08-12 05:59:43
20226,P_1ojkLpCsM8cpuiKlZnAg,Yogurtini,"15601 W Bell Rd, Ste 208",Surprise,AZ,85374,33.637055,-112.398109,4.5,59,...,"Ice Cream & Frozen Yogurt, Food","{'Monday': '11:0-23:0', 'Tuesday': '11:0-23:0'...",4YcRmucsdtcedeiGBuJ0DA,PkFGuK6XuhOceDH30b0xog,5.0,0,0,0,Love this place! Great product and good employ...,2014-09-08 15:22:22

In [60]:
result.to_csv('ice_cream_review.csv')